# Generated by Django 5.1.6 on 2025-03-02 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntenatalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_unit', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('village', models.CharField(max_length=255)),
                ('parish', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('tribe', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
                ('next_of_kin_relationship', models.CharField(max_length=100)),
                ('next_of_kin_address', models.TextField()),
                ('gravida', models.IntegerField()),
                ('para', models.IntegerField()),
                ('abortions', models.IntegerField()),
                ('presenting_complaints', models.TextField(blank=True, null=True)),
                ('first_day_of_lnmp', models.DateField()),
                ('edd', models.DateField()),
                ('weeks_of_amenorrhea', models.IntegerField()),
                ('complications_of_pregnancy', models.TextField(blank=True, null=True)),
                ('hospitalization', models.BooleanField(default=False)),
                ('hospitalization_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AntenatalProgressExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('fundal_height', models.FloatField()),
                ('presentation', models.CharField(max_length=255)),
                ('fetal_heart_rate', models.IntegerField()),
                ('varicose_or_oedema', models.CharField(blank=True, max_length=255, null=True)),
                ('urine_test_results', models.TextField(blank=True, null=True)),
                ('iron_folic_acid_pills', models.IntegerField(blank=True, null=True)),
                ('complaints_and_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('antenatal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_examinations', to='antenental.antenatalcard')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousObstetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_year', models.IntegerField()),
                ('abortions_below_12_weeks', models.IntegerField()),
                ('abortions_above_12_weeks', models.IntegerField()),
                ('premature_births', models.IntegerField()),
                ('full_term_deliveries', models.IntegerField()),
                ('delivery_type', models.CharField(max_length=255)),
                ('place_of_delivery', models.CharField(max_length=255)),
                ('third_stage_complications', models.TextField(blank=True, null=True)),
                ('puerperium', models.TextField(blank=True, null=True)),
                ('baby_alive', models.BooleanField(default=True)),
                ('stillbirth_or_nnd', models.BooleanField(default=False)),
                ('baby_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_weight', models.FloatField()),
                ('immunization_status', models.CharField(max_length=255)),
                ('baby_health_condition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('antenatal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_obstetric_history', to='antenental.antenatalcard')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UltrasoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultrasound_date', models.DateField(default=django.utils.timezone.now)),
                ('gestational_age', models.IntegerField(blank=True, null=True)),
                ('placenta_details', models.TextField(blank=True, null=True)),
                ('amniotic_fluid', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('antenatal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_reports', to='antenental.antenatalcard')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
