# Generated by Django 5.1.6 on 2025-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalcard',
            name='health_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
