# Generated by Django 5.1.6 on 2025-03-02 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_condition', models.CharField(max_length=255)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.TextField()),
                ('prescription_date', models.DateField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateField()),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('cleared_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
