# Generated by Django 5.1.6 on 2025-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0002_alter_antenatalcard_health_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalcard',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
