# Generated by Django 5.1.6 on 2025-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0003_alter_antenatalcard_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalcard',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
