# Generated by Django 5.1.6 on 2025-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0003_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalcard',
            name='next_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
