# Generated by Django 5.1.6 on 2025-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0004_alter_antenatalcard_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalcard',
            name='abortions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='edd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='first_day_of_lnmp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='gravida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='hospitalization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='next_of_kin_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='para',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antenatalcard',
            name='weeks_of_amenorrhea',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
