# Generated by Django 5.1.6 on 2025-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0005_alter_antenatalcard_abortions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
