# Generated by Django 5.1.6 on 2025-03-06 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0006_alter_prescription_follow_up_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('antenatal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='antenental.antenatalcard')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_emergencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
