# Generated by Django 5.1.6 on 2025-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0007_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalcard',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
