# Generated by Django 5.1.6 on 2025-03-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0008_alter_antenatalcard_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalcard',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
