# Generated by Django 5.1.6 on 2025-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenental', '0009_alter_antenatalcard_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalcard',
            name='admitted',
            field=models.BooleanField(default=False),
        ),
    ]
