# Generated by Django 5.1.6 on 2025-03-05 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('health_insurance_details', models.TextField(blank=True, null=True)),
                ('government_scheme_eligibility', models.TextField(blank=True, null=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_hospital', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_address', models.TextField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_field', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_title', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rank_reviews', models.TextField(blank=True, null=True)),
                ('departments', models.TextField(blank=True, null=True)),
                ('bed_availability', models.IntegerField(blank=True, null=True)),
                ('maternity_ward_occupancy', models.IntegerField(blank=True, null=True)),
                ('number_of_healthcare_professionals', models.IntegerField(blank=True, null=True)),
                ('ambulance_response_time', models.CharField(blank=True, max_length=255, null=True)),
                ('specialized_maternity_care', models.TextField(blank=True, null=True)),
                ('delivery_facilities', models.TextField(blank=True, null=True)),
                ('blood_bank_availability', models.BooleanField(default=False)),
                ('room_types_facilities', models.TextField(blank=True, null=True)),
                ('infection_control_measures', models.TextField(blank=True, null=True)),
                ('delivery_package_costs', models.TextField(blank=True, null=True)),
                ('insurance_coverage', models.TextField(blank=True, null=True)),
                ('government_schemes_supported', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('parish', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('date_of_last_period', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('gestational_age', models.IntegerField(blank=True, null=True)),
                ('expected_due_date', models.DateField(blank=True, null=True)),
                ('type_of_pregnancy', models.CharField(blank=True, choices=[('Single', 'Single'), ('Twins', 'Twins'), ('Multiples', 'Multiples')], max_length=20, null=True)),
                ('previous_pregnancies', models.IntegerField(blank=True, null=True)),
                ('delivery_history', models.TextField(blank=True, null=True)),
                ('high_risk_factors', models.TextField(blank=True, null=True)),
                ('fetal_health', models.TextField(blank=True, null=True)),
                ('pre_existing_conditions', models.TextField(blank=True, null=True)),
                ('previous_surgeries', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('diet_preferences', models.TextField(blank=True, null=True)),
                ('exercise_level', models.TextField(blank=True, null=True)),
                ('smoking_alcohol_drug_use', models.TextField(blank=True, null=True)),
                ('mental_health_status', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
