# Generated by Django 5.1.6 on 2025-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted',
            field=models.BooleanField(default=False),
        ),
    ]
